# Generated by Django 5.2 on 2025-04-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='posted_by',
        ),
    ]
