services:
  - type: web
    name: erp-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: echo "=== Running Migrations ===" &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      echo "=== Starting Gunicorn ===" &&
      gunicorn ERP.ERP.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ERP.ERP.settings
      - key: DATABASE_URL
        value: postgresql://erp_db_l9ll_user:7oIqpuFNLtcdLgbw7I7gvK6wdkCXjdyL@dpg-d01kjhadbo4c738rur60-a/erp_db_l9ll
      - key: DEBUG
        value: 'False'
      - key: DJANGO_SECRET_KEY
        value: django-insecure-+0dr_mh&r(fmbnwn)a^%knh06o!ohoa2p*x)pxsz#=qj2b1_)6
